### ISSUE TITLE
possible `CPU` memory leak OOM

### ISSUE THREAD

**Issue by spacegoing** [PKU-YuanGroup/Open-Sora-Plan#445]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/4e0447cf-4be9-4d79-8547-23c6dfda216e">
I'm running a 8-node, 64gpu training task. the cuda memory is fine. the problem is with CPU memory:

as can be seen from the figure, there seems to be a memory leak in cpu memory (**NOT GPU**). my json file for the dataset is ~19GB

Any idea what's the bug?

**Comment by LinB203** [comment]
We are also noticing this problem. It may caused by decord (a package for reading video).

**Comment by spacegoing** [comment]
> We are also noticing this problem. It may caused by decord (a package for reading video).

thank u so much for ur prompt reply.

may I ask what's the workaround?

I also read this: After several iterations, the loader worker processes will consume the same amount of CPU memory as the parent process for all Python objects in the parent process which are accessed from the worker processes. This can be problematic if the Dataset contains a lot of data (e.g., you are loading a very large list of filenames at Dataset construction time) and/or you are using a lot of workers (overall memory usage is number of workers * size of parent process). The simplest workaround is to replace Python objects with non-refcounted representations such as Pandas, Numpy or PyArrow objects. Check out [issue #13246](https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662) for more details on why this occurs and example code for how to workaround these problems.

https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662

**Comment by spacegoing** [comment]
Hi Lin @LinB203 ,

I tried running dataloader alone and the decord lib do have a mem leak issue. I fixed by wrap it with a `with open(filename, 'rb') as f:` clause and solves the issue (would be happy to open a pull request later):

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/a885acd6-c8b5-4d4a-a4d4-cbd21733171c">
running dataloader alone

 as u can see, after fix the memory grows slower, but there still seems to be other mem leak issues, any idea where should I debug first?


<img width="1094" alt="image" src="https://github.com/user-attachments/assets/dd995e6f-19a1-42f9-823d-2c585776a0f2">

**Comment by LinB203** [comment]
We are also solving this now, but we have not solved it.
We are checking [this](https://github.com/RomanArzumanyan/VALI/) now.

**Comment by spacegoing** [comment]
Hi Lin,

tks for ur reply. I guess decord is not the only issue:

I switched to a rust implementation of ffmpeg but the oom issue still persists. I'm also still on this now and will keep u updated.

**Comment by spacegoing** [comment]
@LinB203  Also, my current roadblock is that I can't track issue. I tried to use

 170     def __getitem__(self, idx):                                                                                                                                                                                                   
 171                                                                                                                                                                                                                                   
 172         info = get_worker_info()                                                                                                                                                                                                  
 173         if info is not None:                                                                                                                                                                                                      
 174             if not self.is_start:                                                                                                                                                                                                 
 175                 self.is_start = True                                                                                                                                                                                              
 176             if self.local_step % 5 ==0:                                                                                                                                                                                           
 177                 snapshot = tracemalloc.take_snapshot()                                                                                                                                                                            
 178                 snapshot.dump(f'./worker_snaps/rank_{dist.get_rank()}_wid_{info.id}_step_{self.local_step}.snp')                                                                                                                  
 179      
 
 
 to track mem usage in each dataloader worker, but tracemalloc only tracks ~30 MB mem allocation
 
 Would love to know which mem profiler ru using?
